---
branches:
  only:
    - master
    - develop
    - /^feature/.*$/
language: node_js
node_js:
  - stable
  - "--lts"
env:
  global:
    - CC_TEST_REPORTER_ID=e76c076f5e9770ccb2a6c493f644db0dd5445ecece80288d64bd035f59e2f148
before_install:
  - npm i -g npm
install: npm ci --no-optional
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ $TRAVIS_NODE_VERSION = stable ] && c8 report --reporter=lcov --reporter=text && ./cc-test-reporter
    after-build --debug -t lcov --exit-code $TRAVIS_TEST_RESULT || echo 'Coverage skipped'"
notifications:
  slack:
    secure: vPLEkZ7WN8Xo6pZvPdw7VesYETraEWROy7+b+aPzk4AFp8PHbH7CQ96DJtyseIXbdjUVKChw061BLqs1UwzaW3VDmM7TSsuRrGyExMJ0T5ANO7rVr1uqgwg0TPbPA0G2ZP5d0ArUYoAO4vzU7GRENDYgdqC3waCwfkqgR8TZPhV+HXTw/YnWfUGaOi5Cwtfch7qzL4hN9WpX6ZLkySCq0moxyF72OKfiR4Y2DtPIwTheAJFffauTHyTBiEfiQFsvmSzKuzMDJJ+LTGraJLuivTEVC11nnT17cJ+BXhK79gFOUMYqCbTxxHmKNZ6skWqwhtAOIAziWSDqX0o4ar8iijxdfMxiOeWeG4mIWf26P8bXTey6+AW26SHPvDg+twxuGo7rh5dKsxqSmzjDYzmOlToecf7EOE6+RKVJtykHNBKcAesTfTNx3/1o8Z9EDwmtuyzecWncwA6j0h0tP46AJ9lbcdELAk5e19AD6EU1q/+mZBvDehUtoCYCSt3hEFcOPCN/Soa0rkUEhu2a1FJxfUo15zASwVzFo/kscErnu4D0/J1ii64X2lETOYeJqac3a7ZdWP4ix+7rSKyd12OOEUjSux4nJmTqJ5XcEQzCeh9v9rWcgxne2kD7kZOz6Xtw5yORSeQziL7NRW43esBPtk7MUd6zHfGLdm9FcPd9Kn4=
cache:
  directories:
    - "$HOME/.npm"
